Ext.define('A.soap.Product', {
    extend: 'Ext.data.Model',
    pathURL: '/soap/product',
    idProperty: 'productPrice_id',
    fields: [
        {name: 'id', type: 'int'},
        {name: 'name', type: 'string'},
        {name: 'productCode_id', type: 'int'},
        {name: 'productCode_code', type: 'string'},
        {name: 'brand_id', type: 'int'},
        {name: 'brand_name', type: 'string'},
        {name: 'productPrice_id', type: 'int'},
        {name: 'productPrice_price', type: 'float'},
        {name: 'productPriceDisc', type: 'auto'},
        {name: 'productPriceDisc_desc', type: 'string'},
        {name: 'productPriceDisc_name', type: 'string'},
        {name: 'productPriceDisc_value', type: 'string'},
        {name: 'productPriceTax', type: 'auto'},
        {name: 'productPriceTax_desc', type: 'string'},
        {name: 'productPriceTax_name', type: 'string'},
        {name: 'productPriceTax_value', type: 'string'},
        {name: 'productTag', type: 'auto'},
        {name: 'productTag_name', type: 'string'},
        {name: 'type_id', type: 'int'},
        {name: 'type_name', type: 'string'},
        {name: 'unit_id', type: 'int'},
        {name: 'unit_name', type: 'string'},
        {name: 'unit_shortname', type: 'string'},
        {name: 'status_id', type: 'int'},
        {name: 'status_name', type: 'string'},
        {name: 'notes', type: 'string'},
        {name: 'product_id', type: 'int'},
        {name: 'product_name', type: 'string'}
    ]
});